"""Added vectore_id column in chunk_metadata table.

Revision ID: 0e9e6ed48318
Revises: 91f4332cf648
Create Date: 2025-05-13 21:33:24.031767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9e6ed48318'
down_revision: Union[str, None] = '91f4332cf648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_metadata', sa.Column('vector_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk_metadata', 'vector_id')
    # ### end Alembic commands ###
