"""cascade delete

Revision ID: 7f80c8c7a3cf
Revises: e478f99c410b
Create Date: 2025-05-16 16:42:46.364385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f80c8c7a3cf'
down_revision: Union[str, None] = 'e478f99c410b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunk_metadata', type_='foreignkey')
    op.drop_constraint(None, 'chunk_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'chunk_metadata', 'file_metadata', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk_metadata', 'text_metadata', ['text_metadata_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'text_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'text_metadata', 'file_metadata', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'text_metadata', 'file_metadata', ['file_id'], ['id'])
    op.drop_constraint(None, 'chunk_metadata', type_='foreignkey')
    op.drop_constraint(None, 'chunk_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'chunk_metadata', 'text_metadata', ['text_metadata_id'], ['id'])
    op.create_foreign_key(None, 'chunk_metadata', 'file_metadata', ['file_id'], ['id'])
    # ### end Alembic commands ###
