"""chunk_metadata table addition.

Revision ID: c77b1cba4a24
Revises: 07355ecc7cf4
Create Date: 2025-05-13 14:43:52.680425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77b1cba4a24'
down_revision: Union[str, None] = '07355ecc7cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_metadata_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['text_metadata_id'], ['text_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_metadata_id'), 'chunk_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_metadata_id'), table_name='chunk_metadata')
    op.drop_table('chunk_metadata')
    # ### end Alembic commands ###
